version: '3'
 
services:
    reverseproxy:
        build: ./reverseproxy
        ports:
            - 8080:8080
        depends_on:
            - honeypots

    honeypots:
        build: ./honeypots
        environment:
            - HONEYPOTS_OPTIONS=fix_get_client_ip